OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "your_openai_api_key"

GLMModel:
  model: "glm-4-flash"
  api_key: "your_glm_api_key"

 GeminiModel:
  model: "gemini-1.5-flash"
  api_key: "your_gemini_api_key" 

common:
  book: "tests/test.pdf"
  file_format: "markdown"