OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "your_openai_api_key"

GLMModel:
  model: "glm-4-flash"
  api_key: "your_glm_api_key"
  # timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"